services:
  mongodb:
    image: mongo:latest
    container_name: lesson67-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: lesson67
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  backend:
    image: docker-server-app
    build: ./Server
    ports:
      - "3000:3000"
    volumes:
      - ./Server:/app
      - /app/node_modules
    command: npx nodemon -L src/server.js
    environment:
      - MONGO_URI=mongodb://admin:password123@mongodb:27017/lesson67?authSource=admin
    restart: unless-stopped
    depends_on:
      - mongodb

  frontend:
    image: docker-client-app
    build: ./FrontEnd
    ports:
      - "5173:5173"
    volumes:
      - ./FrontEnd:/app
      - /app/node_modules
    command: npm run start -- --host 0.0.0.0
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  mongodb_data: